version: '2'

services:
  eap-base:
    image: luszczynski/eap-base:latest
    build:
      context: ./eap-base

  eap-domain:
    image: luszczynski/eap-domain
    hostname: eap-domain
    build:
      context: ./eap-domain

  host01:
    image: luszczynski/eap-host
    hostname: host01
    build:
      context: ./eap-host
    depends_on:
      - eap-domain

  host02:
    image: luszczynski/eap-host
    hostname: host02
    build:
      context: ./eap-host
    depends_on:
      - eap-domain

  frontend:
    image: luszczynski/eap-host
    hostname: frontend
    build:
      context: ./eap-host
    depends_on:
      - eap-domain
